/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import Database.Connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Timestamp;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Pocoyo
 */
public class PaymentFormReceipt extends javax.swing.JFrame {
    // Instance variables (add new ones to match your parameters)
    private int userID;
    private String firstName;
    private String lastName;
    private String paymentMethod;
    private String yearsToPay;
    private double calculatedPrice;
    private int lotId;
    private String sqm;
    private String lot;
    private String block;
    private String lotSize;
    private String accountId;
    
    Connection con = Connect.connectdb();

    // Constructor with corrected parameter assignments
    public PaymentFormReceipt(
        int userID,
        String firstName, 
        String lastName, 
        String paymentMethod, 
        String yearsToPay, 
        double calculatedPrice, 
        int lotId,
        String sqm, 
        String lot, 
        String block, 
        String lotSize, 
        String accountId
    ) {
        // Assign parameters to instance variables
        this.userID = userID;
        this.firstName = firstName;
        this.lastName = lastName;
        this.paymentMethod = paymentMethod;
        this.yearsToPay = yearsToPay;
        this.calculatedPrice = calculatedPrice;
        this.lotId = lotId;
        this.sqm = sqm;
        this.lot = lot;
        this.block = block;
        this.lotSize = lotSize;
        this.accountId = accountId;

        initComponents();
        setPaymentReceipt();
    }
    
    private void setPaymentReceipt() {
        fnameField.setText(firstName);
        lnameField.setText(lastName);
        paymentMethodField.setText(paymentMethod);
        yearsField.setText(yearsToPay);
        calculatedPriceField.setText(String.valueOf(calculatedPrice));
        lotIDField.setText(String.valueOf(lotId));
        lotField.setText(lot);
        blockField.setText(block);
        lotTypeField.setText(lotSize);
        sqmField.setText(sqm);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        fnameField = new javax.swing.JTextField();
        lnameLabel = new javax.swing.JLabel();
        lnameField = new javax.swing.JTextField();
        paymentLabel = new javax.swing.JLabel();
        yearsLabel = new javax.swing.JLabel();
        calculatedPriceLabel = new javax.swing.JLabel();
        calculatedPriceField = new javax.swing.JTextField();
        lotLabel = new javax.swing.JLabel();
        blockLabel = new javax.swing.JLabel();
        lotTypeLabel = new javax.swing.JLabel();
        sqmLabel = new javax.swing.JLabel();
        lotIDLabel = new javax.swing.JLabel();
        lotIDField = new javax.swing.JTextField();
        lotField = new javax.swing.JTextField();
        blockField = new javax.swing.JTextField();
        lotTypeField = new javax.swing.JTextField();
        sqmField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        menuBtn = new javax.swing.JButton();
        paymentMethodField = new javax.swing.JTextField();
        yearsField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("PAYMENT RECEIPT");

        fnameLabel.setText("First Name:");

        fnameField.setEditable(false);

        lnameLabel.setText("Last Name:");

        lnameField.setEditable(false);

        paymentLabel.setText("Payment Method:");

        yearsLabel.setText("Years to Pay:");

        calculatedPriceLabel.setText("Calculated Price:");

        calculatedPriceField.setEditable(false);
        calculatedPriceField.setText("...");
        calculatedPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatedPriceFieldActionPerformed(evt);
            }
        });

        lotLabel.setText("Lot");

        blockLabel.setText("Block");

        lotTypeLabel.setText("LotSize");

        sqmLabel.setText("SQM");

        lotIDLabel.setText("Lot ID");

        lotIDField.setEditable(false);
        lotIDField.setText("...");
        lotIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotIDFieldActionPerformed(evt);
            }
        });

        lotField.setEditable(false);
        lotField.setText("...");
        lotField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotFieldActionPerformed(evt);
            }
        });

        blockField.setEditable(false);
        blockField.setText("...");
        blockField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockFieldActionPerformed(evt);
            }
        });

        lotTypeField.setEditable(false);
        lotTypeField.setText("...");

        sqmField.setEditable(false);
        sqmField.setText("...");

        menuBtn.setText("Buy More");
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });

        paymentMethodField.setEditable(false);
        paymentMethodField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentMethodFieldActionPerformed(evt);
            }
        });

        yearsField.setEditable(false);
        yearsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fnameLabel)
                                    .addComponent(fnameField)
                                    .addComponent(lnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lnameField)
                                    .addComponent(paymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(yearsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(calculatedPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(calculatedPriceField)
                                    .addComponent(paymentMethodField)
                                    .addComponent(yearsField))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lotLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lotIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(blockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lotTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sqmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lotIDField)
                                    .addComponent(lotField)
                                    .addComponent(blockField)
                                    .addComponent(lotTypeField)
                                    .addComponent(sqmField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(menuBtn)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameLabel)
                    .addComponent(lotIDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lotIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameLabel)
                    .addComponent(lotLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lotField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentLabel)
                    .addComponent(blockLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentMethodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearsLabel)
                    .addComponent(lotTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lotTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculatedPriceLabel)
                    .addComponent(sqmLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculatedPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sqmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(menuBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lotIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lotIDFieldActionPerformed

    private void lotFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lotFieldActionPerformed

    private void blockFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockFieldActionPerformed

    // HAAAAAAAAAAAAAATERRRRRRSSSSS    
    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        dispose();
        new Buy(userID).setVisible(true);
    }//GEN-LAST:event_menuBtnActionPerformed

    private void calculatedPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatedPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculatedPriceFieldActionPerformed

    private void paymentMethodFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentMethodFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentMethodFieldActionPerformed

    private void yearsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentFormReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentFormReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentFormReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentFormReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Example parameters
                // Example parameters
                int userID = 1;
                String firstName = "Leee";
                String lastName = "Jimenez";
                String paymentMethod = "Credit Card";
                String yearsToPay = "5";
                double calculatedPrice = 50000.00;
                int lotId = 123;
                String sqm = "150";
                String lot = "A10";
                String block = "Block 5";
                String lotSize = "150 sqm";
                String accountId = "1";

                new PaymentFormReceipt(userID, firstName, lastName, paymentMethod, yearsToPay, calculatedPrice, lotId, sqm, lot, block, lotSize, accountId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField blockField;
    private javax.swing.JLabel blockLabel;
    private javax.swing.JTextField calculatedPriceField;
    private javax.swing.JLabel calculatedPriceLabel;
    private javax.swing.JTextField fnameField;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lnameField;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField lotField;
    private javax.swing.JTextField lotIDField;
    private javax.swing.JLabel lotIDLabel;
    private javax.swing.JLabel lotLabel;
    private javax.swing.JTextField lotTypeField;
    private javax.swing.JLabel lotTypeLabel;
    private javax.swing.JButton menuBtn;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JTextField paymentMethodField;
    private javax.swing.JTextField sqmField;
    private javax.swing.JLabel sqmLabel;
    private javax.swing.JTextField yearsField;
    private javax.swing.JLabel yearsLabel;
    // End of variables declaration//GEN-END:variables
}
