package Forms;

import Database.Connect;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author zeldr
 */
public class Reserve extends javax.swing.JFrame {
    
    Connection con= Connect.connectdb();
    
    private String userName;
    /**
     * Creates new form Reserve
     */
    public Reserve(String userName) {
        this.userName = userName;
        initComponents();
        displayLots();
        displayLotSize();
        displayBlock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sizeBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        blockBox = new javax.swing.JComboBox<>();
        reserveLotBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sizeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50", "100" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        reserveLotBtn.setText("Reserve Lot");
        reserveLotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveLotBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reserveLotBtn)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(323, 323, 323))
                    .addComponent(homeBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(sizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(blockBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(homeBtn)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(reserveLotBtn)
                        .addGap(231, 231, 231))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void displayLots() {
        // SQL Statements
        String data = "SELECT * FROM lots";
        
        try (PreparedStatement pStatement = con.prepareStatement(data);
             ResultSet result = pStatement.executeQuery()) {
            jTable1.setModel(DbUtils.resultSetToTableModel(result));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace(); //Good practice to print the stack trace for debugging
        }
    }
    
    public void displayLotSize() {
        String lotsize = "SELECT DISTINCT LotSize FROM Lots";

        try (PreparedStatement pStatement = con.prepareStatement(lotsize);
             ResultSet result = pStatement.executeQuery()) {

            javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();
            model.addElement("Any");

            while (result.next()) {
                model.addElement(result.getString("lotsize"));
            }

            sizeBox.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace(); //Good practice to print the stack trace for debugging
        }
    }
    
    public void displayBlock() {
        String block = "SELECT DISTINCT Block FROM Lots";
        
        try (PreparedStatement pStatement = con.prepareStatement(block);
             ResultSet result = pStatement.executeQuery()) {

            javax.swing.DefaultComboBoxModel<String> model = new javax.swing.DefaultComboBoxModel<>();
            model.addElement("Any");

            while (result.next()) {
                model.addElement(result.getString("Block"));
            }

            blockBox.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace(); //Good practice to print the stack trace for debugging
        }
    }
    
    // This method is used for the Search Button
    public void Search() {
        String baseQuery = "SELECT ID, SQM, Block, Lot, LotSize, Price, COALESCE(Owner, 'None') AS Owner FROM Lots";
        String lotsize = sizeBox.getSelectedItem().toString();
        String block = blockBox.getSelectedItem().toString();
        boolean hasCondition = false;

        if (!"Any".equals(lotsize)) {
            baseQuery += " WHERE LotSize = ?";
            hasCondition = true;
        }

        if (!"Any".equals(block)) {
            if (hasCondition) {
                baseQuery += " AND Block = ?";
            } else {
                baseQuery += " WHERE Block = ?";
            }
        }

        try (PreparedStatement pStatement = con.prepareStatement(baseQuery)) {

            int paramIndex = 1;
            if (!"Any".equals(lotsize)) {
                pStatement.setString(paramIndex++, lotsize);
            }
            if (!"Any".equals(block)) {
                pStatement.setString(paramIndex, block);
            }
            try (ResultSet result = pStatement.executeQuery()) {
                // Display all the rows in the jTable
                jTable1.setModel(DbUtils.resultSetToTableModel(result));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace(); //Good practice to print the stack trace for debugging
        }
    }
    
    public void reserveLot() {
        int row = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please select a lot to reserve.");
            return;
        }
        
        int idAcc = Integer.parseInt(model.getValueAt(row, 0).toString());
        
        String checkOwner = "SELECT Owner FROM Lots WHERE ID = ?";
        String reserveLot = "UPDATE Lots SET Owner = ? WHERE ID = ?";

        try (PreparedStatement psCheck = con.prepareStatement(checkOwner)) {
            psCheck.setInt(1, idAcc);

            try (ResultSet rs = psCheck.executeQuery()) {
                if (rs.next()) {
                    String owner = rs.getString("Owner");

                    if (owner != null && !owner.isEmpty() && !owner.equals("None")) {
                        JOptionPane.showMessageDialog(null, "This lot has already been reserved. Please choose another one.");
                        return; // Important: Exit the method if already reserved
                    } else {
                        // Lot is available, proceed with reservation
                        try (PreparedStatement updateStatement = con.prepareStatement(reserveLot)) {
                            updateStatement.setString(1, userName);
                            updateStatement.setInt(2, idAcc);

                            int affectedRows = updateStatement.executeUpdate();

                            if (affectedRows > 0) {
                                JOptionPane.showMessageDialog(null, "The lot has been reserved!");
                                displayLots(); // Refresh the table
                            } else {
                                JOptionPane.showMessageDialog(null, "Failed to reserve the lot.");
                            }
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, "Error reserving lot: " + ex.getMessage());
                            ex.printStackTrace();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Lot not found.");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error checking owner: " + ex.getMessage());
                ex.printStackTrace();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error preparing statement: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Search();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        dispose();
        new Menu(userName).setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void reserveLotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveLotBtnActionPerformed
        reserveLot();
    }//GEN-LAST:event_reserveLotBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserve("User Name").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> blockBox;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton reserveLotBtn;
    private javax.swing.JComboBox<String> sizeBox;
    // End of variables declaration//GEN-END:variables
}
